TEXTS = {
    'uz': {
        'welcome': "✨ *Gano Shopga xush kelibsiz* ✨\n\nSog'lom mahsulotlar uchun premium manzil.\n\n🛍️ Do'konni ochish uchun pastdagi tugmani bosing.",
        'open_store': "🛍 Do'konni ochish",
        'my_orders': "📦 Mening buyurtmalarim",
        'help': "❓ Yordam",
        'about': "ℹ️ Biz haqimizda",
        'language': "🌐 Til",
        'my_orders_empty': "Sizda hali buyurtmalar yo'q. 🛍️ Do'konni ochib xarid qiling.",
        'my_orders_title': "📋 *Sizning so'nggi buyurtmalaringiz:*\n\n",
        'help_text': "🆘 Yordam kerakmi?\n\nAdmin bilan bog'lanishingiz mumkin: @your_admin_username",
        'about_text': "🌿 *Gano Shop haqida*\n\nTabiiy ingredientlar yordamida salomatlik va farovonlik.",
        'back_to_menu': "🏠 Asosiy menyu",
        'order_summary': "📝 *Buyurtma tarkibi*\n\n{items}\n\n💵 *Jami:* {total} so'm\n\nTasdiqlaysizmi?",
        'continue_order': "✅ Davom etish",
        'cancel_order': "❌ Buyurtmani bekor qilish",
        'ask_contact': "📞 Yetkazib berish uchun telefon raqamingizni ulashing.",
        'ask_location': "📍 Iltimos, aniq yetkazib berish manzilingizni (joylashuvingizni) yuboring.",
        'ask_address': "🏠 To'liq manzilingizni kiriting (ko'cha, uy, kvartira va hokazo):",
        'ask_landmarks': "🗺️ Belgilangan joy yoki qo'shimcha izoh? (Yo'q bo'lsa '-' yuboring)",
        'payment_instructions': "💳 *To'lov yo'riqnomasi*\n\n{total} so'mni quyidagi bank kartasiga o'tkazing:\n`8600 1234 5678 9012`\nQabul qiluvchi: GANO SHOP MChJ\n\nTo'lovdan so'ng chekni (rasm yoki PDF) yuboring.",
        'receipt_success': "✅ *Buyurtma qabul qilindi!*\n\nTez orada menejerimiz siz bilan bog'lanadi.\nRahmat!",
        'receipt_invalid': "Noto'g'ri fayl turi. Chek sifatida rasm yoki PDF yuboring.",
        'order_cancelled_by_user': "Buyurtma bekor qilindi. Yana xarid qilish uchun /start bosing.",
        'order_cancelled_by_admin': "❌ Sizning buyurtmangiz bekor qilindi.\n\nSababini bilish uchun administrator bilan bog'lanishingiz mumkin: @your_admin_username",
        'order_confirmed_by_admin': "✅ Sizning buyurtmangiz tasdiqlandi va ishlov berilmoqda.",
        'admin_new_order': "🛒 *Yangi buyurtma #{order_id}*\n\n👤 *Mijoz:* {name}\n🆔 Telegram ID: `{user_id}`\n📞 Telefon: +{phone}\n\n📦 *Mahsulotlar:*\n{items}\n\n💰 *Jami:* {total} so'm\n\n📍 *Koordinatalar:* {loc}\n🏠 *Manzil:* {addr}\n🗺️ *Belgilar:* {landmarks}\n\n🧾 *Chek:* Yuklandi",
        'admin_map_links': "📍 *Xarita havolalari va amallar:*",
        'admin_confirm': "✅ Buyurtma tasdiqlandi",
        'admin_cancel': "❌ Buyurtma bekor qilindi",
        'admin_panel': "🔐 *Administrator paneli*\n\nQuyidagi amallardan birini tanlang:",
        'admin_export_users': "📥 Foydalanuvchilarni eksport qilish (Excel)",
        'admin_order_stats': "📊 Buyurtma statistikasi",
        'admin_broadcast': "📢 Xabar yuborish (Broadcast)",
        'admin_stats': "📊 *Buyurtma statistikasi*\n\n✅ Tasdiqlangan: {confirmed}\n❌ Bekor qilingan: {cancelled}",
        'admin_broadcast_instruction': "Yubormoqchi bo'lgan xabaringizni matn sifatida yuboring.\nXabar barcha foydalanuvchilarga jo'natiladi.\nBekor qilish uchun /cancel_broadcast yuboring.",
        'admin_broadcast_cancelled': "Xabar yuborish bekor qilindi.",
        'admin_broadcast_sent': "Xabar {count} foydalanuvchiga yuborildi.",
        'error_general': "❌ Xatolik yuz berdi. Iltimos, qaytadan urinib ko'ring.",
        'lang_choice': "🌍 Tilni tanlang / Выберите язык / Choose language:",
        'lang_changed': "Til muvaffaqiyatli o'zgartirildi!",
    },
    'ru': {
        'welcome': "✨ *Добро пожаловать в Gano Shop* ✨\n\nВаш премиальный магазин wellness-продуктов.\n\n🛍️ Нажмите на кнопку ниже, чтобы открыть магазин.",
        'open_store': "🛍 Открыть магазин",
        'my_orders': "📦 Мои заказы",
        'help': "❓ Помощь",
        'about': "ℹ️ О нас",
        'language': "🌐 Язык",
        'my_orders_empty': "У вас пока нет заказов. Начните покупки с 🛍 Открыть магазин.",
        'my_orders_title': "📋 *Ваши последние заказы:*\n\n",
        'help_text': "🆘 Нужна помощь?\n\nСвяжитесь с администратором: @your_admin_username",
        'about_text': "🌿 *О Gano Shop*\n\nМы заботимся о вашем здоровье с помощью натуральных продуктов.",
        'back_to_menu': "🏠 Главное меню",
        'order_summary': "📝 *Состав заказа*\n\n{items}\n\n💵 *Итого:* {total} сум\n\nПодтверждаете?",
        'continue_order': "✅ Продолжить",
        'cancel_order': "❌ Отменить заказ",
        'ask_contact': "📞 Поделитесь своим номером телефона для связи с доставкой.",
        'ask_location': "📍 Теперь отправьте точное местоположение для доставки.",
        'ask_address': "🏠 Введите полный адрес (улица, дом, квартира и т.д.):",
        'ask_landmarks': "🗺️ Ориентиры или комментарии? (Если нет, отправьте '-')",
        'payment_instructions': "💳 *Инструкция по оплате*\n\nПереведите {total} сум на банковскую карту:\n`8600 1234 5678 9012`\nПолучатель: GANO SHOP LLC\n\nПосле оплаты отправьте чек (фото или PDF).",
        'receipt_success': "✅ *Заказ оформлен!*\n\nСкоро с вами свяжется менеджер.\nСпасибо!",
        'receipt_invalid': "Неподдерживаемый тип файла. Отправьте фото или PDF чек.",
        'order_cancelled_by_user': "Заказ отменён. Чтобы сделать новый заказ, нажмите /start.",
        'order_cancelled_by_admin': "❌ Ваш заказ был отменён администратором.\n\nДля уточнения свяжитесь с поддержкой: @your_admin_username",
        'order_confirmed_by_admin': "✅ Ваш заказ подтверждён и обрабатывается.",
        'admin_new_order': "🛒 *Новый заказ #{order_id}*\n\n👤 *Клиент:* {name}\n🆔 Telegram ID: `{user_id}`\n📞 Телефон: +{phone}\n\n📦 *Товары:*\n{items}\n\n💰 *Итого:* {total} сум\n\n📍 *Координаты:* {loc}\n🏠 *Адрес:* {addr}\n🗺️ *Ориентиры:* {landmarks}\n\n🧾 *Чек:* Загружен",
        'admin_map_links': "📍 *Ссылки на карты и действия:*",
        'admin_confirm': "✅ Заказ подтверждён",
        'admin_cancel': "❌ Заказ отменён",
        'admin_panel': "🔐 *Панель администратора*\n\nВыберите действие:",
        'admin_export_users': "📥 Экспорт пользователей (Excel)",
        'admin_order_stats': "📊 Статистика заказов",
        'admin_broadcast': "📢 Рассылка сообщения",
        'admin_stats': "📊 *Статистика заказов*\n\n✅ Подтверждено: {confirmed}\n❌ Отменено: {cancelled}",
        'admin_broadcast_instruction': "Отправьте текст сообщения для рассылки всем пользователям.\nДля отмены отправьте /cancel_broadcast.",
        'admin_broadcast_cancelled': "Рассылка отменена.",
        'admin_broadcast_sent': "Сообщение отправлено {count} пользователям.",
        'error_general': "❌ Произошла ошибка. Попробуйте ещё раз.",
        'lang_choice': "🌍 Tilni tanlang / Выберите язык / Choose language:",
        'lang_changed': "Язык успешно изменён!",
    },
    'en': {
        'welcome': "✨ *Welcome to Gano Shop* ✨\n\nYour premium destination for wellness products.\n\n🛍️ Tap the button below to open the store.",
        'open_store': "🛍 Open Store",
        'my_orders': "📦 My Orders",
        'help': "❓ Help",
        'about': "ℹ️ About",
        'language': "🌐 Language",
        'my_orders_empty': "You have no orders yet. Start shopping with 🛍 Open Store.",
        'my_orders_title': "📋 *Your recent orders:*\n\n",
        'help_text': "🆘 Need assistance?\n\nContact admin: @your_admin_username",
        'about_text': "🌿 *About Gano Shop*\n\nNatural ingredients for your health and well-being.",
        'back_to_menu': "🏠 Main Menu",
        'order_summary': "📝 *Order Summary*\n\n{items}\n\n💵 *Total:* {total} UZS\n\nConfirm?",
        'continue_order': "✅ Continue",
        'cancel_order': "❌ Cancel order",
        'ask_contact': "📞 Share your phone number for delivery communication.",
        'ask_location': "📍 Now share your exact delivery location.",
        'ask_address': "🏠 Enter your full address (street, house, apartment, etc.):",
        'ask_landmarks': "🗺️ Any landmarks or comments? (Send '-' if none)",
        'payment_instructions': "💳 *Payment Instructions*\n\nTransfer {total} UZS to bank card:\n`8600 1234 5678 9012`\nRecipient: GANO SHOP LLC\n\nAfter payment, send the receipt (photo or PDF).",
        'receipt_success': "✅ *Order submitted!*\n\nOur manager will contact you soon.\nThank you!",
        'receipt_invalid': "Unsupported file type. Please send a photo or PDF receipt.",
        'order_cancelled_by_user': "Order cancelled. To place a new order, press /start.",
        'order_cancelled_by_admin': "❌ Your order has been cancelled by the administrator.\n\nFor details, please contact support: @your_admin_username",
        'order_confirmed_by_admin': "✅ Your order has been confirmed and is being processed.",
        'admin_new_order': "🛒 *New Order #{order_id}*\n\n👤 *Customer:* {name}\n🆔 Telegram ID: `{user_id}`\n📞 Phone: +{phone}\n\n📦 *Items:*\n{items}\n\n💰 *Total:* {total} UZS\n\n📍 *Coordinates:* {loc}\n🏠 *Address:* {addr}\n🗺️ *Landmarks:* {landmarks}\n\n🧾 *Receipt:* Uploaded",
        'admin_map_links': "📍 *Map links & actions:*",
        'admin_confirm': "✅ Order confirmed",
        'admin_cancel': "❌ Order cancelled",
        'admin_panel': "🔐 *Admin Panel*\n\nChoose an action:",
        'admin_export_users': "📥 Export users (Excel)",
        'admin_order_stats': "📊 Order statistics",
        'admin_broadcast': "📢 Broadcast message",
        'admin_stats': "📊 *Order statistics*\n\n✅ Confirmed: {confirmed}\n❌ Cancelled: {cancelled}",
        'admin_broadcast_instruction': "Send the message text to broadcast to all users.\nTo cancel, send /cancel_broadcast.",
        'admin_broadcast_cancelled': "Broadcast cancelled.",
        'admin_broadcast_sent': "Message sent to {count} users.",
        'error_general': "❌ An error occurred. Please try again.",
        'lang_choice': "🌍 Tilni tanlang / Выберите язык / Choose language:",
        'lang_changed': "Language changed successfully!",
    }
}